/*
 * gentables.c — build-time generator for src/tables.h
 *
 * Emits the frequency-agnostic rainbow color table and every ANSI escape
 * sequence derived from it, so the hot loop never formats a number.
 *
 * The math mirrors lolcat-ultra's build.rs bit-for-bit (same trig recurrence,
 * same saturating f64->u8 rounding) so both tools paint identical rainbows.
 * Compile with -ffp-contract=off: the Rust original only fuses where it says
 * mul_add, and clang would otherwise contract the plain expressions.
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>

#define TABLE_SIZE 2048

static const double AMPLITUDE = 127.0;
static const double OFFSET = 128.0;
static const double C = -0.5;                    /* cos(2pi/3) */
static const double S = 0.8660254037844386;      /* sin(2pi/3) = sqrt(3)/2 */

/* Branch-free saturating f64 -> u8, matching Rust's `(x.clamp(0,255)+0.5) as u8` */
static uint8_t sat_u8(double x) {
    if (!(x > 0.0)) x = 0.0;
    if (x > 255.0) x = 255.0;
    unsigned t = (unsigned)(x + 0.5);
    return (uint8_t)(t > 255u ? 255u : t);
}

static uint8_t rgb_to_256(uint8_t r, uint8_t g, uint8_t b) {
    if (r == g && g == b) {
        if (r < 8) return 16;
        if (r > 248) return 231;
        return (uint8_t)(232 + ((((unsigned)r - 8) * 25) >> 8));
    }
    unsigned r6 = ((unsigned)r * 5) >> 8;
    unsigned g6 = ((unsigned)g * 5) >> 8;
    unsigned b6 = ((unsigned)b * 5) >> 8;
    return (uint8_t)(16 + 36 * r6 + 6 * g6 + b6);
}

int main(void) {
    uint8_t rgb[TABLE_SIZE][3];

    /* Trig recurrence: one sin_cos, then rotate by delta each step. */
    double delta = 2.0 * M_PI / (double)TABLE_SIZE;
    double sx = 0.0, cx = 1.0;
    double sd = sin(delta), cd = cos(delta);

    for (int i = 0; i < TABLE_SIZE; i++) {
        rgb[i][0] = sat_u8(fma(sx, AMPLITUDE, OFFSET));
        rgb[i][1] = sat_u8(fma(sx * C + cx * S, AMPLITUDE, OFFSET));
        rgb[i][2] = sat_u8(fma(sx * C - cx * S, AMPLITUDE, OFFSET));
        double ns = fma(sx, cd, cx * sd);
        double nc = fma(cx, cd, -sx * sd);
        sx = ns;
        cx = nc;
    }

    printf("/* Generated by tools/gentables.c — do not edit. */\n");
    printf("#ifndef LOLCAT_TABLES_H\n#define LOLCAT_TABLES_H\n\n");
    printf("#include <stdint.h>\n\n");
    printf("#define RAINBOW_SIZE %d\n", TABLE_SIZE);
    printf("#define RAINBOW_MASK %d\n\n", TABLE_SIZE - 1);

    /*
     * TrueColor sequences are "\x1b[38;2;RRR;GGG;BBBm": 19 bytes, zero-padded
     * decimals so every entry is the same width. They are split into a 16-byte
     * head and a 4-byte tail (3 content bytes + a zero pad byte) so the hot
     * loop is exactly one 16-byte store plus one 4-byte store, with the
     * character ORed into the pad slot. Both halves stay naturally aligned.
     */
    printf("/* \"\\x1b[38;2;RRR;GGG;BBBm\" split 16 + 4; tail byte 3 is a zero pad\n"
           "   slot that the following character is ORed into. */\n");
    printf("static const uint8_t TC_HEAD[RAINBOW_SIZE][16] __attribute__((aligned(64))) = {\n");
    for (int i = 0; i < TABLE_SIZE; i++) {
        uint8_t r = rgb[i][0], g = rgb[i][1], b = rgb[i][2];
        uint8_t seq[19] = {
            0x1b, '[', '3', '8', ';', '2', ';',
            (uint8_t)('0' + r / 100), (uint8_t)('0' + r / 10 % 10), (uint8_t)('0' + r % 10), ';',
            (uint8_t)('0' + g / 100), (uint8_t)('0' + g / 10 % 10), (uint8_t)('0' + g % 10), ';',
            (uint8_t)('0' + b / 100), (uint8_t)('0' + b / 10 % 10), (uint8_t)('0' + b % 10), 'm',
        };
        printf("{");
        for (int k = 0; k < 16; k++) printf("%s%u", k ? "," : "", seq[k]);
        printf("},\n");
    }
    printf("};\n\n");

    printf("static const uint32_t TC_TAIL[RAINBOW_SIZE] __attribute__((aligned(64))) = {\n");
    for (int i = 0; i < TABLE_SIZE; i++) {
        uint8_t b = rgb[i][2];
        /* bytes 16,17,18 of the sequence + zero pad, little-endian */
        uint32_t t = (uint32_t)('0' + b / 10 % 10) | ((uint32_t)('0' + b % 10) << 8) |
                     ((uint32_t)'m' << 16);
        printf("%uu,%s", t, (i % 8 == 7) ? "\n" : " ");
    }
    printf("};\n\n");

    printf("/* 256-color palette index for each rainbow slot */\n");
    printf("static const uint8_t C256[RAINBOW_SIZE] __attribute__((aligned(64))) = {\n");
    for (int i = 0; i < TABLE_SIZE; i++) {
        printf("%u,%s", rgb_to_256(rgb[i][0], rgb[i][1], rgb[i][2]), (i % 16 == 15) ? "\n" : "");
    }
    printf("};\n\n");

    printf("/* \"\\x1b[38;5;Nm\" for each palette index, zero-padded to 12 bytes */\n");
    printf("static const uint8_t A256[256][12] __attribute__((aligned(64))) = {\n");
    for (int i = 0; i < 256; i++) {
        char buf[16];
        int n = snprintf(buf, sizeof buf, "\x1b[38;5;%dm", i);
        printf("{");
        for (int k = 0; k < 12; k++) printf("%s%u", k ? "," : "", k < n ? (uint8_t)buf[k] : 0u);
        printf("},\n");
    }
    printf("};\n\n");

    printf("static const uint8_t A256_LEN[256] = {\n");
    for (int i = 0; i < 256; i++) {
        char buf[16];
        int n = snprintf(buf, sizeof buf, "\x1b[38;5;%dm", i);
        printf("%u,%s", (unsigned)n, (i % 16 == 15) ? "\n" : "");
    }
    printf("};\n\n");

    printf("#endif /* LOLCAT_TABLES_H */\n");
    return 0;
}
